# -*- coding: utf-8 -*-
"""StatKomp 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gVGCRthYazgxZ_CGYupyqG8knU6L-dOz

2141720159 / Faradisha Aldina Putri
TI - 2I / 07

MEAN
"""

apel = [100, 200, 150, 100, 120, 80, 90, 160, 110, 170]
total_berat = 0
for i in range (len(apel)):
  total_berat = total_berat + apel[i]

avg_apel = total_berat / len(apel)
print(avg_apel)

import numpy as np
apel = [100, 200, 150, 100, 120, 80, 90, 160, 110, 170]
avg_apel = np.mean(apel)
print(avg_apel)

"""MEDIAN"""

import numpy as np
apel = [100, 200, 150, 100, 120, 80, 90, 160, 110, 170]
med_apel = np.median(apel)
apel.sort()
apel_urut = ' '.join(map(str, apel))
print('Apel urut : {:s}'.format(apel_urut))
print(med_apel)

import math

def bubblesort(elements):
  for n in range(len(elements)-1, 0, -1):
    for i in range(n):
      if elements[i] > elements[i+1]:
        elements[i], elements[i+1] = elements[i+1], elements[i]
  return elements

def calc_median(elements):
  elements = bubblesort(elements)
  len_element = len(elements)
  if len_element % 2 == 0:
    center = math.floor(len_element/2)
    return (elements[center-1] + elements[center]) / 2
  else:
    return elements[math.ceil(len_element/2)-1]

apel = [100, 200, 150, 100, 120, 80, 90, 160, 110, 170]
median = calc_median(apel)
print(median)

"""MODE (MODUS)"""

from scipy import stats
import statistics as s

nilai = [70, 80, 70, 70, 90, 100]

mode_nilai = stats.mode(nilai)
modus = s.mode(nilai)
print(modus)
print(mode_nilai)
print(mode_nilai.mode)

from scipy import stats
import statistics as s

apel = [100, 200, 150, 100, 120, 80, 90, 160, 110, 170]

mode_apel = stats.mode(apel)
modus = s.mode(apel)
print(modus)
print(mode_apel)
print(mode_apel.mode)

"""RANGE"""

import numpy as np 

data = np.array([100, 200, 150, 100, 120, 80, 90, 160, 110, 170])
data_max = max(data)
data_min = min(data)
range = data_max - data_min
print(range)

"""IQR """

import numpy as np 
import pandas as pd

data_baru = np.array([23, 56, 45, 65, 59, 55, 62, 54, 85, 25, 55])
print(pd.DataFrame(data_baru).describe())

"""Scalling

Data Normalization (1)
"""

import numpy as np 
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

data_raw = np.array([
    [2, 3, 7, 30],
    [9, 4, 6, 1],
    [8, 15, 2, 48],
    [20, 10, 2, 6]
])

scaler = MinMaxScaler()
data_scale = scaler.fit_transform(data_raw)

plt.boxplot(data_raw)